name: Build with PyInstaller

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build application
        run: pyinstaller --clean clippy.spec

      - name: Create and Upload Release
        if: startsWith(github.ref, 'refs/tags/')  # Only run on tag pushes
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          tag_name: ${{ github.ref_name }}  # Use just the tag name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
